providers = []
buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1733184274'

[variables]
ELIXIR_ERL_OPTIONS = '+fnu'
MIX_ENV = 'prod'
NIXPACKS_METADATA = 'elixir'
[phases.build]
dependsOn = ['install']
cmds = [
    'mix compile',
    'mix assets.deploy',
    'mix ecto.setup',
]

[phases.install]
dependsOn = ['setup']
cmds = [
    'mix local.hex --force',
    'mix local.rebar --force',
    'mix deps.get --only prod',
]

[phases.setup]
nixPkgs = [
    'elixir_1_14',
    'gcc',
]
nixLibs = ['stdenv.cc.cc.lib']
nixOverlays = []
nixpkgsArchive = 'c5702bd28cbde41a191a9c2a00501f18941efbd0'

[start]
cmd = 'mix phx.server'

